version: "3.3"

services :
  statify:
    depends_on:
      - statifydb
    image: anonomous/statify:latest
    container_name: statifyApp
    links:
     - statifydb:mysql
    ports:
     - "8083:8080"
    volumes:
     - ./MyData:/mnt/docker/MyData
  statifydb:
    image: mariadb
    container_name: statifydb
    ports:
     - "3309:3307"
    environment:
     - MYSQL_ROOT_PASSWORD=bcgFyIWpecKBm6tOPgKWY6YjBs4CLlIxNCUIN4MDnpPjNAfphx
    volumes:
     - ./database:/mnt/docker/mariadb
