version: "2.2"
services:
  statifypma:
    restart: always
    container_name: statifypma
    depends_on:
      - statifydb
    image: phpmyadmin:latest
    networks:
      mynet:
        ipv4_address: 10.5.0.2
    ports:
      - "8084:80"
  statifyapp:
    container_name: statifyapp
    restart: always
    depends_on:
      - statifydb
    image: anonomous/statify
    networks:
      mynet:
        ipv4_address: 10.5.0.3
        aliases:
          - statifyapp
          - app
    ports:
      - "8080:8080"
    volumes:
      - ./MyData:/mnt/docker/MyData
  statifydb:
    container_name: statifydb
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MARIADB_USER=development
      - MARIADB_PASSWORD=wUWDRcJTIHfCu4nj3PaWSVB46pvJw70hDItD78v8dJ
      - MARIADB_DATABASE=statify
      - MARIADB_ROOT_PASSWORD=bcgFyIWpecKBm6tOPgKWY6YjBs4CLlIxNCUIN4MDnpPjNAfphx
    networks:
      mynet:
        ipv4_address: 10.5.0.4
        aliases:
          - db
          - app_db
    volumes:
      - ./mariadb/database:/mnt/docker/mariadb
      - ./mariadb/scripts:/docker-entrypoint-initdb.d
  statifyfront:
    container_name: statifyfront
    image: anonomous/statify-front
    restart: always
    ports:
     - "8081:8081"
    depends_on:
    - statifyapp
    networks:
      mynet:
        ipv4_address: 10.5.0.5
networks:
  mynet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
