# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'liberica'
       

    - name: Build with Maven
      run: mvn clean package --file pom.xml

    - name: Build and push Docker image
      run: mvn spring-boot:build-image
      env :
        push: true
        image: anonomous/statify
        tags: latest
        registry: docker.io
        username: anonomous
        password: dckr_pat_FX4F5XDvB-eCQl0m-eLNR0rYEi8
    